build:
    environment:
        timezone: 'Europe/Berlin'
        postgresql: false
        node: false
        redis: false
        variables:
            COMPOSER_MEMORY_LIMIT: -1

    tests:
        override:
        -   command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
            coverage:
                file: 'clover.xml'
                format: 'clover'

    nodes:

        deps_lowest:
            environment:
                php: '7.2'
            dependencies:
                before:
                    - command: composer update --prefer-lowest
                      idle_timeout: 600
                    
        php_72:
            environment:
                php: '7.2'
